
package com.soap.ws.lb;

import java.math.BigDecimal;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ExchangeRatesSoap", targetNamespace = "http://webservices.lb.lt/ExchangeRates")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ExchangeRatesSoap {


    /**
     * Returns a list of currencies.
     * 
     * @return
     *     returns com.soap.ws.lb.GetListOfCurrenciesResponse.GetListOfCurrenciesResult
     */
    @WebMethod(action = "http://webservices.lb.lt/ExchangeRates/getListOfCurrencies")
    @WebResult(name = "getListOfCurrenciesResult", targetNamespace = "http://webservices.lb.lt/ExchangeRates")
    @RequestWrapper(localName = "getListOfCurrencies", targetNamespace = "http://webservices.lb.lt/ExchangeRates", className = "com.soap.ws.lb.GetListOfCurrencies")
    @ResponseWrapper(localName = "getListOfCurrenciesResponse", targetNamespace = "http://webservices.lb.lt/ExchangeRates", className = "com.soap.ws.lb.GetListOfCurrenciesResponse")
    public com.soap.ws.lb.GetListOfCurrenciesResponse.GetListOfCurrenciesResult getListOfCurrencies();

    /**
     * Returns the current exchange rate (expressed in Litas per 1 currency unit) for the specified currency.
     * 
     * @param currency
     * @return
     *     returns java.math.BigDecimal
     */
    @WebMethod(action = "http://webservices.lb.lt/ExchangeRates/getCurrentExchangeRate")
    @WebResult(name = "getCurrentExchangeRateResult", targetNamespace = "http://webservices.lb.lt/ExchangeRates")
    @RequestWrapper(localName = "getCurrentExchangeRate", targetNamespace = "http://webservices.lb.lt/ExchangeRates", className = "com.soap.ws.lb.GetCurrentExchangeRate")
    @ResponseWrapper(localName = "getCurrentExchangeRateResponse", targetNamespace = "http://webservices.lb.lt/ExchangeRates", className = "com.soap.ws.lb.GetCurrentExchangeRateResponse")
    public BigDecimal getCurrentExchangeRate(
        @WebParam(name = "Currency", targetNamespace = "http://webservices.lb.lt/ExchangeRates")
        String currency);

    /**
     * Returns an exchange rate (expressed in Litas per 1 currency unit) for the specified currency and date.
     * 
     * @param currency
     * @param date
     * @return
     *     returns java.math.BigDecimal
     */
    @WebMethod(action = "http://webservices.lb.lt/ExchangeRates/getExchangeRate")
    @WebResult(name = "getExchangeRateResult", targetNamespace = "http://webservices.lb.lt/ExchangeRates")
    @RequestWrapper(localName = "getExchangeRate", targetNamespace = "http://webservices.lb.lt/ExchangeRates", className = "com.soap.ws.lb.GetExchangeRate")
    @ResponseWrapper(localName = "getExchangeRateResponse", targetNamespace = "http://webservices.lb.lt/ExchangeRates", className = "com.soap.ws.lb.GetExchangeRateResponse")
    public BigDecimal getExchangeRate(
        @WebParam(name = "Currency", targetNamespace = "http://webservices.lb.lt/ExchangeRates")
        String currency,
        @WebParam(name = "Date", targetNamespace = "http://webservices.lb.lt/ExchangeRates")
        String date);

    /**
     * Returns a XML formatted string containing exchange rates for the specified date.
     * 
     * @param date
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "getExchangeRatesByDate_XmlString", action = "http://webservices.lb.lt/ExchangeRates/getExchangeRatesByDate_XmlString")
    @WebResult(name = "getExchangeRatesByDate_XmlStringResult", targetNamespace = "http://webservices.lb.lt/ExchangeRates")
    @RequestWrapper(localName = "getExchangeRatesByDate_XmlString", targetNamespace = "http://webservices.lb.lt/ExchangeRates", className = "com.soap.ws.lb.GetExchangeRatesByDateXmlString")
    @ResponseWrapper(localName = "getExchangeRatesByDate_XmlStringResponse", targetNamespace = "http://webservices.lb.lt/ExchangeRates", className = "com.soap.ws.lb.GetExchangeRatesByDateXmlStringResponse")
    public String getExchangeRatesByDateXmlString(
        @WebParam(name = "Date", targetNamespace = "http://webservices.lb.lt/ExchangeRates")
        String date);

    /**
     * Returns a XML formatted string containing exchange rates for the specified currency that are between specified dates.
     * 
     * @param currency
     * @param dateHigh
     * @param dateLow
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "getExchangeRatesByCurrency_XmlString", action = "http://webservices.lb.lt/ExchangeRates/getExchangeRatesByCurrency_XmlString")
    @WebResult(name = "getExchangeRatesByCurrency_XmlStringResult", targetNamespace = "http://webservices.lb.lt/ExchangeRates")
    @RequestWrapper(localName = "getExchangeRatesByCurrency_XmlString", targetNamespace = "http://webservices.lb.lt/ExchangeRates", className = "com.soap.ws.lb.GetExchangeRatesByCurrencyXmlString")
    @ResponseWrapper(localName = "getExchangeRatesByCurrency_XmlStringResponse", targetNamespace = "http://webservices.lb.lt/ExchangeRates", className = "com.soap.ws.lb.GetExchangeRatesByCurrencyXmlStringResponse")
    public String getExchangeRatesByCurrencyXmlString(
        @WebParam(name = "Currency", targetNamespace = "http://webservices.lb.lt/ExchangeRates")
        String currency,
        @WebParam(name = "DateLow", targetNamespace = "http://webservices.lb.lt/ExchangeRates")
        String dateLow,
        @WebParam(name = "DateHigh", targetNamespace = "http://webservices.lb.lt/ExchangeRates")
        String dateHigh);

    /**
     * Returns a list containing exchange rates for the specified date.
     * 
     * @param date
     * @return
     *     returns com.soap.ws.lb.GetExchangeRatesByDateResponse.GetExchangeRatesByDateResult
     */
    @WebMethod(action = "http://webservices.lb.lt/ExchangeRates/getExchangeRatesByDate")
    @WebResult(name = "getExchangeRatesByDateResult", targetNamespace = "http://webservices.lb.lt/ExchangeRates")
    @RequestWrapper(localName = "getExchangeRatesByDate", targetNamespace = "http://webservices.lb.lt/ExchangeRates", className = "com.soap.ws.lb.GetExchangeRatesByDate")
    @ResponseWrapper(localName = "getExchangeRatesByDateResponse", targetNamespace = "http://webservices.lb.lt/ExchangeRates", className = "com.soap.ws.lb.GetExchangeRatesByDateResponse")
    public com.soap.ws.lb.GetExchangeRatesByDateResponse.GetExchangeRatesByDateResult getExchangeRatesByDate(
        @WebParam(name = "Date", targetNamespace = "http://webservices.lb.lt/ExchangeRates")
        String date);

    /**
     * Returns a Xml Schema of provided Exchange Rates.
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://webservices.lb.lt/ExchangeRates/getExchangeRatesXmlSchema")
    @WebResult(name = "getExchangeRatesXmlSchemaResult", targetNamespace = "http://webservices.lb.lt/ExchangeRates")
    @RequestWrapper(localName = "getExchangeRatesXmlSchema", targetNamespace = "http://webservices.lb.lt/ExchangeRates", className = "com.soap.ws.lb.GetExchangeRatesXmlSchema")
    @ResponseWrapper(localName = "getExchangeRatesXmlSchemaResponse", targetNamespace = "http://webservices.lb.lt/ExchangeRates", className = "com.soap.ws.lb.GetExchangeRatesXmlSchemaResponse")
    public String getExchangeRatesXmlSchema();

    /**
     * Returns a list containing exchange rates for the specified currency that are between specified dates.
     * 
     * @param currency
     * @param dateHigh
     * @param dateLow
     * @return
     *     returns com.soap.ws.lb.GetExchangeRatesByCurrencyResponse.GetExchangeRatesByCurrencyResult
     */
    @WebMethod(action = "http://webservices.lb.lt/ExchangeRates/getExchangeRatesByCurrency")
    @WebResult(name = "getExchangeRatesByCurrencyResult", targetNamespace = "http://webservices.lb.lt/ExchangeRates")
    @RequestWrapper(localName = "getExchangeRatesByCurrency", targetNamespace = "http://webservices.lb.lt/ExchangeRates", className = "com.soap.ws.lb.GetExchangeRatesByCurrency")
    @ResponseWrapper(localName = "getExchangeRatesByCurrencyResponse", targetNamespace = "http://webservices.lb.lt/ExchangeRates", className = "com.soap.ws.lb.GetExchangeRatesByCurrencyResponse")
    public com.soap.ws.lb.GetExchangeRatesByCurrencyResponse.GetExchangeRatesByCurrencyResult getExchangeRatesByCurrency(
        @WebParam(name = "Currency", targetNamespace = "http://webservices.lb.lt/ExchangeRates")
        String currency,
        @WebParam(name = "DateLow", targetNamespace = "http://webservices.lb.lt/ExchangeRates")
        String dateLow,
        @WebParam(name = "DateHigh", targetNamespace = "http://webservices.lb.lt/ExchangeRates")
        String dateHigh);

    /**
     * Returns a average exchange rate for the specified currency, between specified dates.
     * 
     * @param currency
     * @param dateHigh
     * @param dateLow
     * @return
     *     returns com.soap.ws.lb.GetExchangeAvgRateResponse.GetExchangeAvgRateResult
     */
    @WebMethod(action = "http://webservices.lb.lt/ExchangeRates/getExchangeAvgRate")
    @WebResult(name = "getExchangeAvgRateResult", targetNamespace = "http://webservices.lb.lt/ExchangeRates")
    @RequestWrapper(localName = "getExchangeAvgRate", targetNamespace = "http://webservices.lb.lt/ExchangeRates", className = "com.soap.ws.lb.GetExchangeAvgRate")
    @ResponseWrapper(localName = "getExchangeAvgRateResponse", targetNamespace = "http://webservices.lb.lt/ExchangeRates", className = "com.soap.ws.lb.GetExchangeAvgRateResponse")
    public com.soap.ws.lb.GetExchangeAvgRateResponse.GetExchangeAvgRateResult getExchangeAvgRate(
        @WebParam(name = "Currency", targetNamespace = "http://webservices.lb.lt/ExchangeRates")
        String currency,
        @WebParam(name = "DateLow", targetNamespace = "http://webservices.lb.lt/ExchangeRates")
        String dateLow,
        @WebParam(name = "DateHigh", targetNamespace = "http://webservices.lb.lt/ExchangeRates")
        String dateHigh);

}
